/*--------------------------------------------------------------------------------------------------------------------------
Author: Dona Kfoury 
Company: EI-Technologies
Description: Test Class for AP12_Contact
History
<Date>      <Authors Name>   <Brief Description of Change>
--------------------------------------------------------------------------------------------------------------------------*/
@isTest
public class AP12_Contact_Test {
    @isTest
    static void tesUpdateSatisfactionDuClient(){
        /*Test.startTest();
        account myaccount= testUtils.createAccount('testAccount', 'Lebanon', 'Privé');
        insert myaccount;
        List<contact> myContactList= new List<contact>();
        contact mycontact3 = testUtils.createContact('test 2', myaccount.Id, null);
        mycontact3.Indicateur_satisfaction__c='6/10';
        mycontact3.Phone ='45245';
        myContactList.add(mycontact3);
        contact mycontact4 = testUtils.createContact('test 3', myaccount.Id, null);
        mycontact4.Indicateur_satisfaction__c='7/10';
        mycontact4.Phone ='45245';
        myContactList.add(mycontact4);
        insert myContactList ;
        mycontact3.Indicateur_satisfaction__c='8/10';
        update mycontact3;
        delete mycontact4;
        Test.stopTest();   */    
    }
    
}