/*--------------------------------------------------------------------------------------------------------------------------
Author: Jacques Akiki  
Company: EI-Technologies
Description: Class used to update the value of the field  VisionRelationCommercialeTerrain__c with the value of Qualification__c.
History
<Date>      <Authors Name>   <Brief Description of Change>
17/12/2018   Jacques AKiki      Creation
--------------------------------------------------------------------------------------------------------------------------*/
public class AP42_Account 
{
   public static void UpdateVisionRelation(List<Account> ListAcc)
    {
		/*for (Account Acc : ListAcc ) 
        {
            //if (Acc.QualitePartenaire__c <>NULL && Acc.VisionRelationCommercialeTerrain__c ==NULL)
            //{
               // Acc.VisionRelationCommercialeTerrain__c = Acc.QualitePartenaire__c ;
            //}
            
            if (Acc.Qualification__c <>NULL && Acc.VisionRelationCommercialeTerrain__c ==NULL)
            {
                Acc.VisionRelationCommercialeTerrain__c = Acc.Qualification__c ;
            }
        }*/
    }
}