public class lwc05EcosystemePartenaire_Wrapper {
    /*@AuraEnabled
       public String PartenaireLieName {get; set;}
       @AuraEnabled
       public String PartenaireURL {get; set;}*/
    @AuraEnabled
    public String TypeRelation {get; set;}
    @AuraEnabled
    public String ContratName {get; set;}
    @AuraEnabled
    public String ContratURL {get; set;}
    @AuraEnabled
    public Double ContratCAEnCours {get; set;}
    @AuraEnabled
    public String OppName {get; set;}
    @AuraEnabled
    public String OpportunityURL {get; set;}
    @AuraEnabled
    public Double OpportuniteCAOffre {get; set;}
    @AuraEnabled
    public String Statut {get; set;}
}