public with sharing class lwc12CustomDataTable_Wrapper {
		@AuraEnabled 
    	public string dkCode {get; set;}
        @AuraEnabled 
    	public string nomEmplacement {get; set;}
        @AuraEnabled 
    	public string ville {get; set;}
        @AuraEnabled 
    	public string codePostal {get; set;}
        @AuraEnabled 
    	public string usage {get; set;}
        @AuraEnabled 
    	public string numeroContrat {get; set;}
}