global class Validation_Opportunity 
{
    public static boolean blnAlreadyDone = false; 
    public static boolean blnAlreadyDone2 = false; 
    public static boolean blnAlreadyDone3 = false;
    public static boolean blnAlreadyDone4 = false;
    public static boolean blnAlreadyDone5 = false;
    public static boolean blnAlreadyDone6 = false;
    public static boolean blnAlreadyDone7 = false;
    public static boolean blnAlreadyDone8 = false;
    public static boolean blnAlreadyDone9 = false;
    public static boolean hasAlreadyDone()
    { 
        return blnAlreadyDone; 
    }
    
    public static void setAlreadyDone() 
    {
        blnAlreadyDone = true;
    } 
    public static boolean hasAlreadyDone2()
    { 
        return blnAlreadyDone2; 
    }
    
    public static void setAlreadyDone2() 
    {
        blnAlreadyDone2 = true;
    }
    public static boolean hasAlreadyDone3()
    { 
        return blnAlreadyDone3; 
    }
    
    public static void setAlreadyDone3() 
    {
        blnAlreadyDone3 = true;
    }
    public static boolean hasAlreadyDone4()
    { 
        return blnAlreadyDone4; 
    }
    
    public static void setAlreadyDone4() 
    {
        blnAlreadyDone4 = true;
    }
    public static boolean hasAlreadyDone5()
    { 
        return blnAlreadyDone5; 
    }
    
    public static void setAlreadyDone5() 
    {
        blnAlreadyDone5 = true;
    }
    public static boolean hasAlreadyDone6()
    { 
        return blnAlreadyDone6; 
    }
    
    public static void setAlreadyDone6() 
    {
        blnAlreadyDone6 = true;
    }
    public static boolean hasAlreadyDone7()
    { 
        return blnAlreadyDone7; 
    }
    
    public static void setAlreadyDone7() 
    {
        blnAlreadyDone7 = true;
    }
     public static boolean hasAlreadyDone8()
    { 
        return blnAlreadyDone8; 
    }
    
    public static void setAlreadyDone8() 
    {
        blnAlreadyDone8 = true;
    }
     public static boolean hasAlreadyDone9()
    { 
        return blnAlreadyDone9; 
    }
    
    public static void setAlreadyDone9() 
    {
        blnAlreadyDone9 = true;
    }
}