public class ValidateWSFields {
    public static Response validateTextField(String fieldName, Integer fieldSize, string value, Response resp){
        /*if(fieldName.length() > fieldSize){
            resp.reponseCode = 'KO';
            resp.errorText += 'La taille du champ ' + fieldName + 'peut etre au plus ' + fieldSize + '\n';
            resp.error = true;
            return resp;
        }
        else {*/
            return resp;
        //}
    }
}